### PR TITLE
[Add] Proposal for a Out that can be used to paginate the result

### PR DESCRIPTION
**Pull request by alejoloaiza**
Hi Saddam, please consider this proposal, let me know your comments. Thanks.
https://github.com/thedevsaddam/gojsonq/issues/42

### CODE REVIEW

**Comment by thedevsaddam** [comment]
@alejoloaiza It would be better to set `Offset` method, the result will be reflected on the outputs.

Please send PR against dev branch and cover the code tests.

**Comment by alejoloaiza** [comment]
sure, just gimme a couple of days to do the adjustments i'm having tons of work, cheers.

**Comment by thedevsaddam** [comment]
Hey I've already added the feature in dev branch, you may help me to ensure the feature is okay.

**Comment by thedevsaddam** [comment]
As this feature added in [v2.2.0](https://github.com/thedevsaddam/gojsonq/releases/tag/v2.2.0), I'm closing the PR.

Thank you very much for the effort (Y)

**Pull request closed without merging**
