### PR TITLE
Add more error info on As() function

### PR DESCRIPTION
**Pull request by cifren**
## issue
When using : 
```golang
tempTags = []Tag{} // Structure
jsonResult.As(&tempTags)
```
This error is displayed an error from reflect library: 
```
panic: reflect: call of reflect.Value.Call on zero Value [recovered]
        panic: reflect: call of reflect.Value.Call on zero Value
```

## Expected
Should display a more specific error that give us more clues in order to understand what is going on

```
Panic: the method '*[]repository.Tag' must be part of 'map[*[]bool:BoolSlice *[]float32:Float32Slice *[]float64:Float64Slice *[]int:IntSlice *[]int16:Int16Slice *[]int32:Int32Slice *[]int8:Int8Slice *[]string:StringSlice *[]time.Duration:DurationSlice *[]uint:UintSlice *[]uint16:Uint16Slice *[]uint32:Uint32Slice *[]uint8:Uint8Slice *bool:Bool *float32:Float32 *float64:Float64 *int:Int *int16:Int16 *int32:Int32 *int8:Int8 *string:String *time.Duration:Duration *uint:Uint *uint16:Uint16 *uint32:Uint32 *uint8:Uint8]' [recovered]
        panic: the method '*[]repository.Tag' must be part of 'map[*[]bool:BoolSlice *[]float32:Float32Slice *[]float64:Float64Slice *[]int:IntSlice *[]int16:Int16Slice *[]int32:Int32Slice *[]int8:Int8Slice *[]string:StringSlice *[]time.Duration:DurationSlice *[]uint:UintSlice *[]uint16:Uint16Slice *[]uint32:Uint32Slice *[]uint8:Uint8Slice *bool:Bool *float32:Float32 *float64:Float64 *int:Int *int16:Int16 *int32:Int32 *int8:Int8 *string:String *time.Duration:Duration *uint:Uint *uint16:Uint16 *uint32:Uint32 *uint8:Uint8]'
```

### CODE REVIEW

**Comment by cifren** [comment]
I am not sure if I understand that coverage message... can you explain ?

**Comment by Dragomir-Ivanov** [comment]
Hi @cifren 
Sorry for the late response. You should add test case that tests the code branch you added. 
In your particular case is to add test case where `methodMap[method]`  is empty, e.g. `==""`.

**Comment by thedevsaddam** [comment]
@cifren You must create an issue and discuss it with others about the problem before sending PR.

I think we can add an error and stop panicking

> https://github.com/thedevsaddam/gojsonq/blob/master/CONTRIBUTING.md

**Comment by thedevsaddam** [comment]
@cifren I fixed the issue. Please update the package to [v2.5.0](https://github.com/thedevsaddam/gojsonq/releases/tag/v2.5.0)

and closing the PR. 

Thank you :)

**Comment by cifren** [comment]
You are right panicking was a little too much, an error is better.

Thank you for your help.

**Pull request closed without merging**
